diplom
EvgeniyBudaev/yandex-go-musthave-diploma-tpl pull request #1
Opened 2023-11-19 06:14 UTC by EvgeniyBudaev

2023-11-23 21:15 UTC, kilchik requested changes

2023-11-23 21:15 UTC, kilchik commented on internal/config/config.go
> +var ServerAddr string
Глобальных переменных быть не должно - тебе ничего не мешает их сделать локальными

2023-11-23 21:15 UTC, kilchik commented on internal/db/db.go
> +	m, err := migrate.New("file://internal/db/migrations", dbURI)
Путь лучше задавать через конфиг, на худой конец - положить в константу

2023-11-23 21:15 UTC, kilchik commented on internal/db/migrations/000001_user_order_tables.up.sql
> +    amount real,
Деньги нужно хранить либо в копейках в целочисленных типах, либо в decimal. Иначе при операциях над real будут накапливаться погрешности, чего мы хотим избежать при работе с деньгами

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +var UserCookie = "UserCookie"
Это константа

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +var UserID = userCtxName("UserID")
Глобальных переменных быть не должно

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +		log.Printf("error while casting order to int %s", err.Error())
Хватит ли тебе информации в логах для расследования? Предлагаю взять структурированный логер (например, zap) и добавить все параметры в вывод, которые могут пригодиться

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +	if orderNum < 0 {
В этой функции смешение логики - и математические операции и присвоение статус кодов - нужно разнести

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +func ValidateOrder(order string) (uint, int) {
Все функции и переменные, которые не нуждаются в экспорте, следует сделать неэкспортируемыми - снижая область видимости, мы уменьшаем связность компонентов и добавляем дополнительные проверки на этапе компиляции

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +	for orderNumber := range strg.ordersToProcess {
Слишком много логики в одной функции - код плохо читается и невозможно написать лаконичные юнит-тесты. Следует выделить функцию получения статуса заказа

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +			if newOrder.Status != "INVALID" && newOrder.Status != "PROCESSED" {
Строковые константы следует вынести в типизированные константы

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +	h := hmac.New(sha256.New, CookieKey)
Следует выделить отдельную функцию для генерации куки

2023-11-23 21:15 UTC, kilchik commented on internal/handlers/handlers.go
> +	defer r.Body.Close()
В хэндлерах тело не нуждается в явном закрытии

2023-11-23 21:15 UTC, kilchik commented on internal/storage/storage.go
> +	row := s.db.QueryRow("SELECT id, login, password_hash FROM \"user\" WHERE login = $1", a.Login)
Все запросы в БД должны быть с контекстом, пробрасываемым из запроса

2023-11-23 21:15 UTC, kilchik commented on internal/storage/storage.go
> +		return http.StatusInternalServerError
Статус коды семантически никак не относятся к хранилищу - такая смесь логики приводит к жесткой связности компонентов контроллера и хранилища - теряется весь смысл отдельного пакета. На этом уровне следует определить набор ошибок, которые могут быть возвращены из методов storage, и обрабатывая их на уровне выше, выбирать подходящий код для клиента

2023-12-02 18:29 UTC, kilchik requested changes

2023-12-02 18:29 UTC, kilchik commented on internal/config/config.go
> +var config Config
Глобальных переменных быть не должно (даже на уровне одного пакета)

2023-12-02 18:29 UTC, kilchik commented on internal/handlers/handlers.go
> +const statusInvalid = "INVALID"
Лучше сделать типизированные константы, чтобы переложить на компилятор дополнительную проверку типа, иначе в функцию можно передать неправильную строковую константу, и она будет обработана
```
type orderStatus string
const (
  orderStatusInvalid orderStatus = "INVALID"
  orderStatusProcessed = "PROCESSED"
)
```

2023-12-02 18:29 UTC, kilchik commented on internal/handlers/handlers.go
> +func ValidateOrder(order string) (uint, int) {
?

2023-12-02 18:29 UTC, kilchik commented on internal/handlers/handlers.go
> +		log.Printf("error while casting order to int %s", err.Error())
?

2023-12-02 18:29 UTC, kilchik commented on internal/handlers/handlers.go
> +	if orderNum < 0 {
?

2023-12-02 18:29 UTC, kilchik commented on internal/handlers/handlers.go
> +				time.Sleep(1 * time.Second)
Следует использовать время из заголовка Retry-After

2023-12-02 18:29 UTC, kilchik commented on internal/storage/storage.go
> +func GetStorage(dbDSN string) Storage {
В Go идиоматично функции, инициализирующие структуры, принято называть New...: если из пакета возвращается какой-то один основной объект, то просто New(), если разные - NewStorage()

2023-12-02 18:29 UTC, kilchik commented on internal/storage/storage.go
> +	} else {
else не нужен

2023-12-02 18:29 UTC, kilchik commented on internal/storage/storage.go
> +	h := sha256.New()
Метод хранилища ничего не должен знать про генерацию хэша - это прерогатива сервисного слоя или просто отдельного пакета, который используется на вышележащем уровне.

2023-12-02 18:29 UTC, kilchik commented on internal/storage/storage.go
> +			return http.StatusOK, nil
На уровне хранилища не должно быть статус кодов

2023-12-02 18:29 UTC, kilchik commented on internal/storage/storage.go
> +		} else {
else не нужен

2023-12-02 18:29 UTC, kilchik commented on internal/utils/cookie.go
> +package utils
Пакет utils/misc/etc - муветон, как правило, в таком пакете образуется свалка семантически несвязанных методов/констант и т д, что приводит к плохой читаемости, сильной связности компонентов и циклическим зависимостям. Функция для генерации cookie может быть в пакете auth вместе с другими функциями и структурами, относящимся к аутентификации

2023-12-04 13:41 UTC, EvgeniyBudaev commented on internal/storage/storage.go
> +			return http.StatusOK, nil
Не получается избавиться в этом методе, т.к. тесты не проходят в дальнейшем. В остальных местах поправил статус коды

2023-12-04 13:44 UTC, EvgeniyBudaev commented on internal/utils/cookie.go
> +package utils
Поправил

2023-12-04 13:44 UTC, EvgeniyBudaev commented on internal/storage/storage.go
> +		} else {
Поправил

2023-12-04 13:44 UTC, EvgeniyBudaev commented on internal/storage/storage.go
> +	h := sha256.New()
Поправил

2023-12-04 13:45 UTC, EvgeniyBudaev commented on internal/storage/storage.go
> +	} else {
Поправил

2023-12-04 13:48 UTC, EvgeniyBudaev commented on internal/storage/storage.go
> +func GetStorage(dbDSN string) Storage {
Поправил

2023-12-04 13:55 UTC, EvgeniyBudaev commented on internal/handlers/handlers.go
> +				time.Sleep(1 * time.Second)
Поправил

2023-12-04 13:56 UTC, EvgeniyBudaev commented on internal/handlers/handlers.go
> +const statusInvalid = "INVALID"
Поправил

2023-12-04 17:00 UTC, EvgeniyBudaev commented on internal/config/config.go
> +var config Config
Поправил

2023-12-07 16:59 UTC, kilchik requested changes

2023-12-07 16:59 UTC, kilchik commented on internal/storage/storage.go
> +			return http.StatusOK, nil
Теста никак не зависят от расположения статус кодов в коде - значит что-то не так в вызывающей функции

2023-12-07 16:59 UTC, kilchik commented on internal/handlers/handlers.go
> +					strg.ordersToProcess <- orderNumber
Представь, что кто-то/что-то перезапустит сервис, а заказ так и подвис в канале, не успев обновиться до терминального статуса в БД - получим неправильное состояние хранилища, что может быть фатально для нашего продукта. Попробуй переделать логику так, что даже при рестарте у тебя все заказы дойдут до терминального статуса. Например, в storage у тебя уже есть метод GetOrdersInProgress, но он нигде не используется - вероятно он тебе пригодится

2023-12-09 09:38 UTC, EvgeniyBudaev commented on internal/handlers/handlers.go
> +					strg.ordersToProcess <- orderNumber
Всё поправил

2023-12-11 04:57 UTC, merged